### ISSUE TITLE
Arrays are botched in the current version

### ISSUE THREAD

**Issue by dslomov** [dslomov/typed-objects-es7#1]
I realized I completely botched arrays. 
In current spec, typed object is a tuple of (typeObject, dimensions,  buffer, offset, opacity) and SameValue is SameValue pairwise (dimensions are not JS object so it is just list equality). And TypeObject includes dimensions as well.

This is of course wrong. What we need is a TypeDescriptor entity. TypeDescriptor is a real JS object and includes:
- structure
- rank
- prototype
- opacity

StructTypes are TypeDescriptors, as well as S.Array. (So some type objects are TypeDescriptors and some are not). Type descriptors for arrays are cached. 

Then a typed object is a tuple of (typeDescriptor, dimensions, buffer, offset, opacity).
typedObject.[[GetPrototypeOf]] = typeDescripror.prototype.

**Comment by nikomatsakis** [comment]
It might be helpful to discuss how I plan to IMPLEMENT this part of
the spec.

Given our grammar:

```
T = U | [T x N]
P = U | [P]
U = int | ... | { f: T, ... }
```

I plan for type objects (`T`) to be JS objects. Each one will have a
(immutable) link to a prototype (`P`). The prototype will be a special
JS object that carries in its private state all the information about
the type which is described. The only exception is the dimensions for
an array, naturally, which are carried in the type object.

When you instantiate a type object, it will carry a pointer to the
_prototype_, not the type object. For non-array prototypes, the prototype
will also have a back-pointer to the type object, which is used for the
`objectType()` function. For array prototypes, we'll have to synthesize
the result for `objectType()` as previously discussed.

It sounds like my prototypes correspond to your "type descriptor", but
I'm not sure.

**Comment by dslomov** [comment]
Almost. I envisioned the "prototype" object for struct types to be the type object itself (let me call your "prototype"  a "type descriptor" because prototype is a thing in JS). So it is the most immutable of links,

So "type descriptors" need to be real JS objects (or at least there is a 1:1 correspondence between type descriptors and a set of JS objects):
- for struct types, it is the type object itself
- for array types, it is S.Array

typeDesignator.prototype then gives a real prototype object (in JS sense).

**Comment by nikomatsakis** [comment]
OK. This makes sense -- basically, in exactly those cases where (in my description) a prototype would have a back-pointer to the original type object, you make those two things the same object.

**Comment by dslomov** [comment]
I mostly rewrote the spec to match "type descriptor" idea; but not it occurred to me that the better idea would be to make the "type descriptor" an actual prototype object. In that case there is no conflating of type object and type descriptor - every type object has its type descriptor as a (readonly nonconfiguable) "prototype" property.

**Comment by nikomatsakis** [comment]
@dslomov-chromium that's precisely what I meant (and is precisely what I'm doing in the actual impl)

**Comment by dslomov** [comment]
Very cool - I'll spec that!

**Comment by dslomov** [comment]
Done.
