### ISSUE TITLE
Settle name of `ArrayType` or `arrayType` method

### ISSUE THREAD

**Issue by nikomatsakis** [dslomov/typed-objects-es7#8]
When trying to write examples I found that `typeObj.ArrayType()` seems to read very strangely to me. Now that we have the `Type` suffix, I think we should just make all methods start with a lower case letter.

@dslomov-chromium opinions?

**Comment by nikomatsakis** [comment]
Same for `opaqueType()` and `OpaqueType()`

**Comment by dslomov** [comment]
SGTM. arrayType and opaqueType it is.

**Comment by nikomatsakis** [comment]
i made this change in that latest PR.
